name: create-release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  setup-release-jellyfin-plugin:
    name: "Setup Release: Jellyfin Plugin"
    uses: forgejo/workflows/.forgejo/workflows/release-jellyfin-plugin.yaml@main
    with:
      dotnet-version: 9.0.x
      dotnet-framework: net9.0
      test-command: dotnet test BetterPosters.sln --configuration Release --verbosity normal
